spring.application.name=auth-service
server.port=8080

# properties
spring.datasource.url=jdbc:postgresql://localhost:5432/homeworkout_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

jwt.secret=verysecretkey12345
jwt.expiration-ms=3600000
